definitions:
  main.Error:
    properties:
      msg:
        type: string
    type: object
  main.NewThing:
    description: Request body for a new 'thing`
    properties:
      name:
        description: The name of the new thing
        example: my new thing
        minLength: 5
        type: string
    required:
    - name
    type: object
  main.Thing:
    description: An object of the 'Thing' model
    properties:
      created_at:
        description: The time this thing was created at
        type: string
      flooble:
        description: |-
          Flooble holds the obviously important flooble value of this thing,
          which is unique to this thing and should be cherished
        type: integer
      id:
        description: The id of this Thing
        type: string
      name:
        description: The name of this thing
        type: string
      status:
        description: The status of this thing, in enum ['creating', 'created', 'error']
        enum:
        - creating
        - created
        - error
        type: string
      updated_at:
        description: The time this thing was updated at
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - application/json
      description: create a new thing
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: New thing
        in: body
        name: thing
        required: true
        schema:
          $ref: '#/definitions/main.NewThing'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Thing'
        "400":
          description: The input object failed validation
          schema:
            $ref: '#/definitions/main.Error'
        "401":
          description: Missing or Invalid Authorization Token
          schema:
            $ref: '#/definitions/main.Error'
        "429":
          description: Too many requests
          schema:
            type: string
      summary: create a new thing
      tags:
      - New
  /{id}:
    delete:
      description: |-
        Delete a thing from the thing API
        Note: this endpoint will fail if the thing does not exist
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Thing ID, see the ID field from a new Thing
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: The thing was successfully deleted
          schema:
            type: string
        "401":
          description: Missing or Invalid Authorization Token
          schema:
            $ref: '#/definitions/main.Error'
        "404":
          description: This thing does not exist
          schema:
            $ref: '#/definitions/main.Error'
        "429":
          description: Too many requests
          schema:
            type: string
      summary: delete a thing
      tags:
      - Delete
    get:
      description: Load a thing from the thing API
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Thing ID, see the ID field from a new Thing
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Thing'
        "401":
          description: Missing or Invalid Authorization Token
          schema:
            $ref: '#/definitions/main.Error'
        "404":
          description: This thing does not exist
          schema:
            $ref: '#/definitions/main.Error'
        "429":
          description: Too many requests
          schema:
            type: string
      summary: load a thing
      tags:
      - Get
swagger: "2.0"
